<?php
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CommunesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $communes = [
           ["name" => "NGAOUNDAL", "departement_id" => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TIBATI", "departement_id" => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAYO-BALEO", "departement_id" => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TIGNERE", "departement_id" => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GALIM-TIGNERE", "departement_id" => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KONTCHA", "departement_id" => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANYO", "departement_id" => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANKIM", "departement_id" => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAYO-DARLE", "departement_id" => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MEIGANGA", "departement_id" => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DJOHONG", "departement_id" => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIR", "departement_id" => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAOUI", "departement_id" => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAOUNDERE 1er", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAOUNDERE 2e", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAOUNDERE 3e", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BELEL", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBE", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGANHA", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NYAMBAKA", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MARTAP", "departement_id" => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBANDJOCK", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MINTA", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NANGA-EBOKO", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKOTENG", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIBEY", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NSEM", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LEMBE-YEZOUM", "departement_id" => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EVODOULA", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MONATELE", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OBALA", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OKOLA", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SA'A", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ELIG-MFOMO", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EBEBDA", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BATSCHENGA", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOBO", "departement_id" => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFIA", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOKITO", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DEUK", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAKENENE", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDIKINIMEKI", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OMBESSA", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KIIKI", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KON-YAMBETTA", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NITOUKOU", "departement_id" => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NTUI", "departement_id" => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAMBE", "departement_id" => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGORO", "departement_id" => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YOKO", "departement_id" => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBANGASSINA", "departement_id" => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MFOU", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ESSE", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AWAE", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SOA", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AFANLOUM", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ASSAMBA", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EDZENDOUAN", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKOLAFAMBA", "departement_id" => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOUMOU", "departement_id" => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKONO", "departement_id" => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBANKOMO", "departement_id" => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIKOK", "departement_id" => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE I", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE II", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE III", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE IV", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE V", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE VI", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAOUNDE VII", "departement_id" => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOT-MAKAK", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ESEKA", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAKAK", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MESSONDO", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOG-MAPUBI", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MATOMB", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIBANG", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGUIBASSAL", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BONDJOCK", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIYOUHA", "departement_id" => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKONOLINGA", "departement_id" => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AYOS", "departement_id" => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ENDOM", "departement_id" => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MENGANG", "departement_id" => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAKOKOMBO", "departement_id" => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DZENG", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBALMAYO", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOMEDZAP", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKOEMAN", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MENGUEME", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKOL-METET", "departement_id" => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOLOUNDOU", "departement_id" => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SALAPOUMBE", "departement_id" => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GARI-GOMBO", "departement_id" => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SALAPOUMBE", "departement_id" => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ABONG-MBANG", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUME", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOMIE", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MESSAMENA", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGUELEMENDOUKA", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIMAKO", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOYLA", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BEBEND", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBOUANZ", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DJA", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUMAINTANG", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MESSOK", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SAMALOMO", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOMA", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BENDENG", "departement_id" => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BATOURI", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDELELE", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KETTE", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBANG", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDEM-NAM", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOMBE", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBOTORO", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SO", "departement_id" => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BERTOUA 1er", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BERTOUA 2e", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BETARE-OYA ", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BELABO", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GAROUA-BOULAÏ", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIANG", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MANDJOU", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOURA", "departement_id" => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOGO", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAROUA 1er", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAROUA 2e", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAROUA 3e", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MERI", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GAZAWA", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "PETTE", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DARGALA", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUKOULA", "departement_id" => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOUSSERI", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAKARY", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOGONE-BIRNI", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GOULFEY", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WAZA", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FOTOKOL", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "HILE-HALIFA", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BLANGOUA", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DARAK", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ZINA", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NYANON", "departement_id" => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KAR-HAY", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DATCHEKA", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YAGOUA", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GUERE", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAGA", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KALFOU", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WINA", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "VELE", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TCHATIBALI", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GOBO", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KAÏ-KAÏ", "departement_id" => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KAELE", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GUIDIGUIS", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MINDIF", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOUTOURWA", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOULVOUDAYE", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "PORHI", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TAIBONG", "departement_id" => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MORA", "departement_id" => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TOKOMBERE", "departement_id" => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOLOFATA", "departement_id" => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOKOLO", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BOURRHA", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOZA", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "HINA", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOGODE", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAYO-MASKOTA", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SOULEDE-ROUA", "departement_id" => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIBOMBARI", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOUM", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MANJO", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBANGA", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MELONG", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKONGSAMBA 1er", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKONGSAMBA 2e", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKONGSAMBA 3e", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NLONAKO", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BARE-BAKEM", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NJOMBE-PENJA", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ABO", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOMBO", "departement_id" => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKONDJOCK", "departement_id" => 27, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YABASSI", "departement_id" => 27, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "YINDI", "departement_id" => 27, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NORD-MAKOMBE", "departement_id" => 27, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIZANGE", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EDEA 1er", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EDEA 2e", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDOM", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGAMBE", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "POUMA", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MOUANKO", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIBAMBA", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGWEI", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NYANON", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MASSOCK-SONGLOULOU", "departement_id" => 28, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 1er", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 2e", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 3e", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 4e", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 5e", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DOUALA 6", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MANOKA", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GAROUA 1er", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GAROUA 2e", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GAROUA 3e", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIBEMI", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "PITOA", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LAGDO", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DEMBO", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MANOKA", "departement_id" => 29, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TCHEBOA", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAYO HOURNA", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BASHEO", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TOUROUA", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BASCHEO", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DEMSA", "departement_id" => 30, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "POLI", "departement_id" => 31, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BEKA", "departement_id" => 31, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GUIDER", "departement_id" => 32, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "PAYO-OULO", "departement_id" => 32, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FIGUIL", "departement_id" => 32, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "REY-BOUBA", "departement_id" => 33, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TCHOLLIRE", "departement_id" => 33, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TOUBORO", "departement_id" => 33, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MADINGRING", "departement_id" => 33, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FUNDONG", "departement_id" => 34, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BELO", "departement_id" => 34, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BUM", "departement_id" => 34, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NJINIKOM", "departement_id" => 34, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "JAKIRI", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KUMBO", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OKU", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBVEN", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NONI", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NONI", "departement_id" => 35, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKAMBE", "departement_id" => 36, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NWA", "departement_id" => 36, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKO", "departement_id" => 36, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MISAJE", "departement_id" => 36, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDU", "departement_id" => 36, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WUM", "departement_id" => 37, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FURU-AWA", "departement_id" => 37, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MENCHUM VALLEY", "departement_id" => 37, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FUNGOM", "departement_id" => 37, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAMENDA 1er", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAMENDA 2e", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAMENDA 3e", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BALI", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TUBAH", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFUT", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SANTA", "departement_id" => 38, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BATIBO", "departement_id" => 39, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBENGWI", "departement_id" => 39, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NJIKWA", "departement_id" => 39, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGIE", "departement_id" => 39, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WIDIKUM-MENKA", "departement_id" => 39, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NDOP", "departement_id" => 40, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BABESSI", "departement_id" => 40, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BALIKUMBAT", "departement_id" => 40, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MBOUDA", "departement_id" => 41, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "GALIM", "departement_id" => 41, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BATCHAM", "departement_id" => 41, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BABADJOU", "departement_id" => 41, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFANG", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANA", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANDJA", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KEKEM", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAKOU", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANKA", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANWA", "departement_id" => 42, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAHAM", "departement_id" => 43, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAMENDJOU", "departement_id" => 43, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANGOU", "departement_id" => 43, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BATIE", "departement_id" => 43, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "POUMOUGNE", "departement_id" => 44, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAYANGAM", "departement_id" => 44, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DJEBEM", "departement_id" => 44, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DSCHANG", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "PENKA-MICHEl", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FOKOUE", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NKONG-NI", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SANTCHOU", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FONGO TONGO", "departement_id" => 45, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFOUSSAM 1er", "departement_id" => 46, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFOUSSAM 2e", "departement_id" => 46, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAFOUSSAM 3e", "departement_id" => 46, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANGANGTE", "departement_id" => 47, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAZOU", "departement_id" => 47, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TONGA", "departement_id" => 47, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BASSAMBA", "departement_id" => 47, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FOUMBAN", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FOUMBOT", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MALENTOUEN", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MASSANGAM", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MAGBA", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOUTABA", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANGOURAIN", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOUOPTAMO", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NJIMON", "departement_id" => 48, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BENGBIS", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DJOUM", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "SANGMELIMA", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ZOETELE", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OVENG", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MINTOM", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MEYOMESSALA", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MEYOMESSI", "departement_id" => 49, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EBOLOWA 1er", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EBOLOWA 2e", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIWONG-BANE", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MVANGAN", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MENGONG", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGOULEMAKONG", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EFOULAN", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIWONG BULU", "departement_id" => 50, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKOM II", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "CAMPO", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KRIBI 1er", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KRIBI 2e", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOLODORF", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MVENGUE", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BIPINDI", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LOKOUNDJE", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NIETE", "departement_id" => 51, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AMBAM", "departement_id" => 52, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MA'AN", "departement_id" => 52, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "OLAMZE", "departement_id" => 52, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KYE OSSI", "departement_id" => 52, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MUYUKA", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TIKO", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LIMBE 1er", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LIMBE 2e", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "LIMBE 3e", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BUEA", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WEST-COAST", "departement_id" => 53, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BANGEM", "departement_id" => 54, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "NGUTI", "departement_id" => 54, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TOMBEL", "departement_id" => 54, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "FONTEM", "departement_id" => 55, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ALOU", "departement_id" => 55, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "WABANE", "departement_id" => 55, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "AKWAYA", "departement_id" => 56, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EYUMODJOCK", "departement_id" => 56, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "UPPER-BAYANG", "departement_id" => 56, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KUMBA 1er", "departement_id" => 57, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KUMBA 2e", "departement_id" => 57, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KUMBA 3e", "departement_id" => 57, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KONYE", "departement_id" => 57, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BONGE", "departement_id" => 57, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "BAMUSSO", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "EKONDO-TITI", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "ISANGUELE", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "MUNDEMBA", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOMBO ABEDIMO", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "KOMBO IDINTI", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "IDABATO", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "DIKOME-BALUE", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
           ["name" => "TOKO", "departement_id" => 58, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
       ];

        DB::table('communes')->insert($communes);
    }
}
